;programa que le o codigo das teclas de um teclado e exibe no LCD
;variaveis

VALOR EQU 33H
LED1 EQU P1.0
LED2 EQU P1.1
;-----------------------------------------
ORG 0000H
	LJMP MAIN    
;==============================================
$INCLUDE (LCDSBV.INC)
$INCLUDE(TECLADO.INC)
;=====================================================
MAIN:
	MOV SP, #50H ; AJUSTE PONT PILHA
	MOV P1,#0F0H ; APAGA OS LEDS
	CALL INITLCD ; INICIALIZA O LCD
	MOV A,#82H
	CALL CMDOLCD ;ENVIA O COMANDO
	MOV DPTR, #FRASEINICIO
	CALL MENSAGE ;ESCREVE A FRASE NO LCD
START:
    CALL LER_TECLADO  ;UMA VARREDURA
	JZ START     ; SE ZERO LER NOVAMENTE: 0=NENHUMA TECLA PRESSIONADA
	
TESTA_TECLA1:
    CJNE A, #31, TESTA_TECLA2
    SETB LED1
    CLR LED2
	MOV A,#0C0H
	CALL CMDOLCD ;ENVIA O COMANDO
	MOV DPTR, #FRASELED1
	CALL MENSAGE ;ESCRVE A FRASE NO LCD
    JMP FIM

TESTA_TECLA2:
    CJNE A, #41, FIM
    SETB LED2
    CLR LED1
	MOV A,#0C0H
	CALL CMDOLCD ;ENVIA O COMANDO
	MOV DPTR, #FRASELED2
	CALL MENSAGE ;ESCRVE A FRASE NO LCD	
    JMP FIM
FIM:
	JMP START
FRASEINICIO:  
	DB "STATUS LED:"
	DB 00H
FRASELED1:  
    DB "LED1=L - LED2=D"
    DB 0000H
FRASELED2:
    DB "LED1=D - LED2=L"
    DB 0000H			 
END;
		  